### ISSUE TITLE
No error/notification message when a file fails to upload

### ISSUE THREAD

**Issue by cgarofalo** [classic-o/nova-media-library#12]
**The bug**
When uploading a file larger than what is allowed in the config, the Media Manager will refuse to upload the image, and no error / notification is shown as to why.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set size limit in the config for images. 
`'max_size' => [
		'Image' => 2097152,
		'Docs'  => 5242880,
	],`
2. Try uploading a an image larger than what is allowed. (In this case, limit is 2 MBs).
3. Image will not upload. No message as to why is given. "Uploaded files: 0/1" green pop appears. 

There should be a warning, something like "The file you tried to upload is larger than 2MBs".

**Comment by classic-o** [comment]
Added notification and file name, which can not upload in 0.4.1.
But without detail. E.g.: **File size limit exceeded (500.svg)**
I dont know, do we need to say more details about error. Because admin must know about limits :)

**Comment by cgarofalo** [comment]
@classic-o 

Thanks, I'll update the package on my project.

Even though we advise our clients of what the limits are, they need to be reminded why their file uploads are failing. We get a lot of angry / false bug reports / time wasting emails. 🤷‍♀
