### ISSUE TITLE
List view

### ISSUE THREAD

**Issue by Sorion** [classic-o/nova-media-library#14]
**Describe the solution you'd like**
It would be great to have an option to switch from "card view" (as it is now) to a list view inside the view (not in conf). It would be handful especially for document. If possible having the name, date of upload and maybe size ? 
All these fields are well provided in the database

Thanks,

**Comment by classic-o** [comment]
Hi, do you talking about media library page or in post page? Do You want enable list in ML page with extra data?

**Comment by classic-o** [comment]
Maybe I'll do it, but a later. Thank You.
