### ISSUE TITLE
Media Field shows blank value when a single video file selected

### ISSUE THREAD

**Issue by 8ix** [classic-o/nova-media-library#16]
- Laravel Version: 5.8.35
- Nova Version: 2.4.0
- PHP Version: 7.3
- Browser type and version: Chrome v77

**Description**
When setting the Media picker field against a resource using: 
`MediaField::make('video')` if a MP4 or video is selected the file name is not shown against the selected item. 

**To Reproduce**
1. Go to resource where media picker is set and select video file
3. No file name shown, just options to clear or reselect. 

**Screenshots**
![Screenshot 2019-10-17 at 10 07 39](https://user-images.githubusercontent.com/2439738/66994998-1f402880-f0c6-11e9-8ee2-23aadef661fd.png)

**Comment by classic-o** [comment]
Fixed in 0.5.1
