### ISSUE TITLE
ADDING TRANSLATE PT-BR  

### ISSUE THREAD

**Issue by nibri10** [classic-o/nova-media-library#19]
** I did the translation to portuguese from Brazil and I would like you to include the package support, a word that I could not translate because I did not find the key was this:**

@pxlrbt @classic-o 

**Following the translation file thank you in advance**

![image](https://user-images.githubusercontent.com/22533877/68230602-1ad9a200-ffd8-11e9-8d0a-ab5e3277ed50.png)

[pt-br.zip](https://github.com/classic-o/nova-media-library/files/3810338/pt-br.zip)

**Comment by wemersonrv** [comment]
hey man. Good job!

**Comment by nibri10** [comment]
I solved all the problems with the translation I hope you can add the Portuguese as a translation @pxlrbt @classic-o

**Comment by pxlrbt** [comment]
Hey @nibri10,
I'm not the maintainer of this project, so I can't integrate your code. Ideally you create a fork of this project, add your translation and create a pull request from your fork.

**Comment by nibri10** [comment]
the owner doesn't allow me to pull @pxlrbt

**Comment by pxlrbt** [comment]
@nibri10 That's not how it works. You should **fork** the repository. Then apply the changes in your own version of the repository. When you're done: Create a pull request for merging your changes into the main repository.

**Comment by classic-o** [comment]
Hi, I will add this file tomorrow

**Comment by nibri10** [comment]
ok, open new pull request with translations for pt-br now
