### ISSUE TITLE
API::upload response

### ISSUE THREAD

**Issue by pwronline** [classic-o/nova-media-library#20]
Wouldn't it be better if the API::upload returned the path of the image or an json with values?

Other issue
I am having problems with the multiple selector. Anyone else?

Great job Pavel.

**Comment by classic-o** [comment]
> Wouldn't it be better if the API::upload returned the path of the image or an json with values?

No, I think its ok. This function i did for automatic works (for example cron`s). For this we dont need to know uploaded path. If you need, you can see this files in media library.

> I am having problems with the multiple selector. Anyone else?

What do you mean?
