### ISSUE TITLE
Bulk select checkbox covers whole thumbnail

### ISSUE THREAD

**Issue by pxlrbt** [classic-o/nova-media-library#22]
When activating bulk select, the checkbox is covering the whole image, so you don't see which images to select.

**To Reproduce**
1. Open Modal
2. Click on "Bulk select"

**Screenshots**
![image](https://user-images.githubusercontent.com/22632550/70934801-09f06780-203f-11ea-8bf8-82bae09f2353.png)

**Comment by classic-o** [comment]
Sorry, my bad. Fixed in 0.5.4
