### ISSUE TITLE
Select Image size to be used when displaying images in Media Library view.  

### ISSUE THREAD

**Issue by Riggs1992** [classic-o/nova-media-library#24]
I want to be able to set an image size in config/media-library.php to be used when displaying images in the media library view. 

Right now it's using the original size that results in huge amounts of data and unnecessary long loading times when browsing large uploaded images.

**Comment by classic-o** [comment]
Hi. Do you want to have thumbnail in Tool? Or set for field?
If for tool, in v1 will be thumbnail for admin area.
I think it will be this month.

**Comment by Riggs1992** [comment]
In the Tool, yes. 

Ah okay, sounds great. Do you have any ETA for v1 release?

**Comment by classic-o** [comment]
This/Next month
