### ISSUE TITLE
Array list/gallery not visible in Nova

### ISSUE THREAD

**Issue by upperhouse** [classic-o/nova-media-library#29]
An array of either 'gallery' or 'list' is not visible after saving resource. Both versions are visible when first adding to the field before saving, but then after saving only the "Select Files" button is visible. The actual array of ids is persistent in the database, which is set as a column of nullable text, it just doesn't seem to be rendering within Nova when editing the resource. The items are also not in the list view, in the manner that is demonstrated in the readme. I was able to replicate this on two different installs of Laravel 7 with Nova 3.0.1. Single images are working as expected.

![image](https://user-images.githubusercontent.com/325781/77862606-e8744f80-71d9-11ea-82eb-a3c7404cf586.png)

![image](https://user-images.githubusercontent.com/325781/77862612-f033f400-71d9-11ea-9920-336333a01c18.png)

Sorry, if I am just missing something simple.
Thank you for the great tool!

**Comment by classic-o** [comment]
Hi. Did you set **$casts**?

**Comment by upperhouse** [comment]
That was the problem, sorry for the bother.
Thank you!
