### ISSUE TITLE
Unable to store media ID instead of URL

### ISSUE THREAD

**Issue by cgarofalo** [classic-o/nova-media-library#31]
The documentation states that it is possible to save media with its ID instead of the URL. `In your model stores only id of file(s).` The documentation is missing on how to actually accomplish this. I would rather store the media ID, so that I can have access to the data stored in the `nova_media_library` table.

Ultimately the goal is to display the file size in the view. (Required for accessibly).

**Comment by classic-o** [comment]
Hi. when You choose file and save model, in your table store only ID of file from `nova_media_library ` table. If you want to get all data of file from nml table - use `$file = API::getFiles(1, null, true);`

**Comment by cgarofalo** [comment]
Sorry, that doesn't make any sense.

This is my field in Nova:

`MediaField::make('PDF', 'pdf')->withTypes(['PDF'])->hideFromIndex()`

By default, the URL is saved to the 'pdf' column of my database for this model. I want it to save the ID instead. Is there a hidden function that I need to call something like `->saveAsId()` ? Is there a configuration setting that I'm missing? Do I need to setup and observer to intercept Nova saving my model?

Please clarify. Thank you.

**Comment by classic-o** [comment]
Version of library? store as ID in table since 1.x
