### ISSUE TITLE
Other folders in storage/app showing

### ISSUE THREAD

**Issue by svenvanhees** [classic-o/nova-media-library#32]
**Describe the bug**
While viewing the medialibrary in Nova and having specified a storage folder in the config file, it is showing other folders I have in my storage/app folder. See the screenshots.

**Screenshots**
![image](https://user-images.githubusercontent.com/3237025/80601509-36c17c00-8a2e-11ea-9b44-88564570bc82.png)

![image](https://user-images.githubusercontent.com/3237025/80601647-5f497600-8a2e-11ea-82c6-c7ec8ec15551.png)

![image](https://user-images.githubusercontent.com/3237025/80601810-94ee5f00-8a2e-11ea-8139-a2a790f3e6e4.png)

**Additional context**

**Comment by classic-o** [comment]
Hi. When you use **local** disk - **folder** param does not work
Change disk to **public** and set **folder** param.

**Comment by svenvanhees** [comment]
That does seem to be the issue, but that would also mean the uploaded files are accessibel publicly. I also tried to add a custom disk, but it has the same issue,

Any way we can have folders, and a custom disk?

**Comment by classic-o** [comment]
You can move your hidden files to *storage* folder
If you use *local* disk - you will see all files in *storage/app*
