### ISSUE TITLE
Access private S3 objects via CloudFront URL instead of private tool URL

### ISSUE THREAD

**Issue by justindantzer** [classic-o/nova-media-library#33]
This feature is not directly related to something malfunctioning, but something not functioning in an ideal way.

My S3 bucket is set to private, and so Nova Media Library requires I have `private` set to `true`. However, instead of using the `nova-media-library.url` config option, based on the `AWS_URL` env value, the URL is created using the `nml-private-file` route in the tool. In my case, CloudFront should be handling access to the private objects at S3.

It would be ideal to optionally override that private route, or choose not to use the private route and use the normal URL format, even if configured to use `private` mode.

**Comment by classic-o** [comment]
Hi. Sorry, but not now :(
