### ISSUE TITLE
Add embed media type

### ISSUE THREAD

**Issue by Slgoetz** [classic-o/nova-media-library#35]
**Is your feature request related to a problem? Please describe.**
Overall this library is fantastic, but we are looking for a way to include media that is not fully hosted on our system such as embeds of videos. 

**Describe the solution you'd like**
It would be great if you could specify an embed upload where you would essentially add a title, the embed url, and potentially some custom meta info and that would be saved the media library. This way you could use the same piece of media all over your site and manage the embed url from a single source.

**Comment by classic-o** [comment]
Hi, for embed, you can use another library. This tool only for store and manage files
