### ISSUE TITLE
Allow to open images in modal

### ISSUE THREAD

**Issue by timdiels1** [classic-o/nova-media-library#39]
**Is your feature request related to a problem? Please describe.**
Hi, the module is awesome! But it feels like a little incomplete. I would like to open images not in a new windows, but in a modal or colorbox like solution.

**Describe the solution you'd like**
When clicking on an image on a resource detail view, the image should be opened in a modal.

**Describe alternatives you've considered**
None

**Additional context**
None.

**Comment by classic-o** [comment]
Hi. May be in future. But not now :(
