### ISSUE TITLE
Impossible to save

### ISSUE THREAD

**Issue by piep14** [classic-o/nova-media-library#4]
It's impossible to save ... Link between Resource and Media ?  Thx

![Capture](https://user-images.githubusercontent.com/3505174/57087561-9b090d00-6d00-11e9-863c-7fd7f8a78e19.PNG)

**Comment by classic-o** [comment]
Hi, can you give me more information (your resource and model), I don't understand what happened.

**Comment by piep14** [comment]
Resource : Nava/Document.php 

`
use ClassicO\NovaMediaLibrary\MediaField;

public function fields(Request $request)
    {
        return [
            Text::make('Nom', 'name')->sortable(),
            
            MediaField::make('Image', 'image'),
        ];
    }
`

Model.php

I did not edit this file. 
What should you do in the Model?

**Comment by classic-o** [comment]
From error I understood: Your table in the database does not have an `image` column.

**Comment by piep14** [comment]
Ok, so that's what I thought, we must add image in each table?

And on the FRONT page, just read this new field

**Comment by classic-o** [comment]
Yes, you need add column in your db table for save any data :) (in each table, where need add image\gallery, you need add column, where images will be storedю
You also can rename this column
