### ISSUE TITLE
TinyMCE5 integration

### ISSUE THREAD

**Issue by Apatrid** [classic-o/nova-media-library#41]
I created Nova TinyMCE5 editor integration field which works well with the Nova Media Library so you can use TinyMCE editor and insert images from Nova Media Library into your content.

Check it out here: [Nova TinyMCE5 Editor](https://github.com/Kraftbit/nova-tinymce5-editor)

**Comment by classic-o** [comment]
Good. But I don't support this library yet. Maybe in the future
