### ISSUE TITLE
Provide possibility to add localizable ALT text for images

### ISSUE THREAD

**Issue by ChrisAluani** [classic-o/nova-media-library#48]
# Feature Request
We would highly appreciate the possibility to add **additional (translatable) Nova fields**  to an image. We would require this functionality to provide _localized ALT texts for SEO and accessibility_ purposes.

Something similar to https://github.com/ebess/advanced-nova-media-library "Custom Properties" would be great.

<img width="969" alt="Bildschirmfoto 2020-11-20 um 10 50 00" src="https://user-images.githubusercontent.com/11610638/99786950-685f7900-2b1f-11eb-9c17-ba2cb69469f5.png">

__Sidenote:__ We really like this library a lot more than the project I just referenced, but this is the only thing that is missing from our perspective. Thanks in advance!

**Comment by classic-o** [comment]
Hi. Now I am not working on this project. May be in future. I have a lot of idea, but have no time :(

**Comment by ChrisAluani** [comment]
@classic-o Alright, thanks for the quick response. Would you provide a short guideline and review/accept a PR if we decide to try to implement it ourselves ?

**Comment by classic-o** [comment]
Copy my project and do everything what you want. Maybe next year I will start development 2.x version
