### ISSUE TITLE
Remove configuration value for URL

### ISSUE THREAD

**Issue by harmenjanssen** [classic-o/nova-media-library#50]
**Is your feature request related to a problem? Please describe.**
Laravel is capable of figuring out the URL to a file itself. It's a small annoyance to have to introduce a new environment variable because this package creates the URL to a file itself instead of using Laravel's build-in methods.

**Describe the solution you'd like**
I can create a Pull Request which will update `ClassicO\NovaMediaLibrary\Core\Model::getUrlAttribute` to use `Storage::disk('foo')->url('bar.jpg')`.

**Describe alternatives you've considered**
If this approach has already been considered, and there are issues I'm unaware of, please let me know!

**Additional context**
Laravel documentation: https://laravel.com/docs/5.8/filesystem#file-urls

**Comment by classic-o** [comment]
Hi. Yes, maybe it's my mistake) But I think it's not a big problem for now. Will change in a future.
