### ISSUE TITLE
Error The PutObject operation requires non-empty parameter Bucket

### ISSUE THREAD

**Issue by tylerpixelguild** [classic-o/nova-media-library#51]
**Describe the bug**
I have the filesystem disk set to "S3" and have specified the s3 URL but not sure if that is set correctly. 

When I try to upload an image I get the error "The PutObject operation requires non-empty parameter Bucket". 

I have the following vars set in my .env

S3_BUCKET=XXXXX
S3_PREFIX=XXXXX
S3_URL=https://s3.amazonaws.com/
S3_GET_IMAGE_URL=XXXXX
AWS_URL=XXXXX

Can you post an example of .env vars I need to set in order to use s3 for storage?

**Comment by classic-o** [comment]
Hi.
Because you did not set needed parameters.
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=
AWS_BUCKET=
AWS_URL=
