### ISSUE TITLE
Direct to S3 file uploads on Laravel Vapor

### ISSUE THREAD

**Issue by natbentley** [classic-o/nova-media-library#54]
At the moment, if using Laravel Nova in conjunction with Laraval Vapor, there's a pretty low limit on file upload size (around a couple of MB) - this is due to the limits with AWS Lambda.  Laravel Nova offers a mechanism for file uploads to Vapor, using a direct to S3 method, documented here (https://nova.laravel.com/docs/3.0/resources/fields.html#vapor-image-field) and here (https://docs.vapor.build/1.0/resources/storage.html#file-uploads)

It would be great if nova-media-library could support this feature to allow uploads of greater file size on the Vapor platform, especially as the rest of the feature-set is something we absolutely love, and really want to integrate into our projects!

**Comment by classic-o** [comment]
Sorry, but I never worked with Vapor and there is no time to study

**Comment by natbentley** [comment]
Totally understood @classic-o - if I get time to figure it out myself and raise a PR, would you be interested in that?

**Comment by martin-ro** [comment]
@natbentley did you figured something out?

**Comment by natbentley** [comment]
Not yet - wanted to check you'd be ok with me submitting a PR - I'm off for a week now, but will take a look when I'm back.
