### ISSUE TITLE
How to keep the original file name when uploading files

### ISSUE THREAD

**Issue by liucf** [classic-o/nova-media-library#56]
Thank you for this excellent nova package.

Right now, if upload a file, it will add some random string to the end of file name automatically. 
How to prevent it? So keep the the original file name?

Also, the menu is showing at the bottom of the navigation sidebar right now. Can I set the position where to show it?

Thank you.

**Comment by classic-o** [comment]
Hi.
1. Yes I added random key in the end of path for prevent the same names (yes, may be I will change it in feature version). Unfortunately you cant change it (only rewrite my package :) )
2. I know how we can change order of resources only... You can change order of all items in menu by CSS style: flex and order
