### ISSUE TITLE
Migration rollback: Set down() method 

### ISSUE THREAD

**Issue by mizmiz** [classic-o/nova-media-library#57]
**Is your feature request related to a problem? Please describe.**
Running ```php artisan migrate:rollback``` and ```php artisan migrate``` again results in error ``` Base table or view already exists: 1050 Table 'media' already exists…```

**Describe the solution you'd like**
Add  
```
/**
 * Reverse the migrations.
 *
 * @return void
 */
public function down()
{
    Schema::dropIfExists('media');
}
```
to migration

**Comment by classic-o** [comment]
https://github.com/classic-o/nova-media-library/blob/master/database/2020_01_01_000000_create_nova_media_library_table.php
I have this code in migration
