### ISSUE TITLE
Unexpected folders appearing

### ISSUE THREAD

**Issue by sutcliffe121** [classic-o/nova-media-library#59]
Problem:
When I view my media library in Nova - I see folders that I do not expect to see.

Expected Behaviour:
In the nova-media-library config file, I have defined the folder of storage as 'medialibrary'. So when I view my media library in Nova, I expect to see folders created within this folder only.

Actual Behaviour:
When I view my media library in Nova, I see folders which are outside of the defined 'medialibrary' folder. These are other folders from the 'storage/app/public' directory.

**Screenshots**
Config:
![image](https://user-images.githubusercontent.com/33236577/104223027-01818080-543b-11eb-897b-f8cbebbe4cc5.png)

Folder Structure:
![image](https://user-images.githubusercontent.com/33236577/104223107-1cec8b80-543b-11eb-9ba2-946f340fc5f7.png)

storage/app/public/medialibrary - contents:
![image](https://user-images.githubusercontent.com/33236577/104223568-b9169280-543b-11eb-99a9-eed97e39eac7.png)

storage/app/public/images - contents:
![image](https://user-images.githubusercontent.com/33236577/104223545-ad2ad080-543b-11eb-97b0-8eea528a50c8.png)

Nova View:
![image](https://user-images.githubusercontent.com/33236577/104223367-72289d00-543b-11eb-8bb5-94ad7d43ee1c.png)

Why are the subfolders in 'storage/app/public/images' appearing when I view my media library in nova when I have defined my media library folder as 'storage/app/public/medialibrary'?

I don't expect to see the folders highlighted:
![image](https://user-images.githubusercontent.com/33236577/104223875-1f9bb080-543c-11eb-88f7-ed67408300fb.png)

**Comment by classic-o** [comment]
Fixed in 1.0.6

**Comment by sutcliffe121** [comment]
Perfect, working as expected now with 1.0.6 update.

Thanks - great package.
