### ISSUE TITLE
Some Kind Of Integration With Rich Text Fields

### ISSUE THREAD

**Issue by nickpoulos** [classic-o/nova-media-library#6]
This package would be absolutely perfect...with a way to drag an image or group of them, into a rich text field, Trix, Trumbowyg, Froala, etc. There are a lot of choices now, which may make a universal solution difficult, but even a way to make it possible to integrate that functionality with your richtext of choice, would be huge.  👍 

Thanks for a great package.

**Comment by classic-o** [comment]
Hi, thanks for the idea. Now there is no time for this package. But I have a few more ideas and in the near future I plan to continue developing this module.

**Comment by Apatrid** [comment]
I'll feel free to ask here.

I managed to connect Nova Media Library via JS callback function and insert images from library to CKEditor 5, but now I am wondering is there a way to open Media Library modal directly from CKEdior custom button and hide Nova Media Library JS callback field?

If you can help with me with an idea how could I open Media Library modal with JavaScript from a custom CKEditor button, it would be much appreciated.

I am attaching a screenshot of what I implemented for a better understanding.

![media-library-cke5](https://user-images.githubusercontent.com/3986799/85542795-ba0be200-b619-11ea-9150-f7ccc065b48a.png)

Thank you!

**Comment by Apatrid** [comment]
I also needed this,but I don't like Trix so I created Nova TinyMCE5 editor integration field which works well with your Nova Media Library. Check it out here: [Nova TinyMCE5 Editor](https://github.com/Kraftbit/nova-tinymce5-editor)
