### ISSUE TITLE
Feature Req: Ability to update media library item

### ISSUE THREAD

**Issue by sutcliffe121** [classic-o/nova-media-library#62]
Feature request. Great package. I receive very good feedback from my users, however, there is a specific use case which is not catered for but I think would be a great enhancement. 

Use case:
- User uploads a PDF file. This generates a unique URL http://mydomain.com/factsheet-instrument-restricted-rating-1613049539HC0Wf.pdf and a unique file ID in the database.
- I have hyperlinks to the PDF file in 5 different content pages on my site, using the unique URL above (or I use the API to get the file by its ID).
- The user notices a spelling mistake in the PDF and updates it.

Current behaviour:
- User cannot update the existing media library item. 
- User has to upload the amended PDF file which results in a different URL and a different file ID.
- I have to update all of the hyperlinks.

Requested behaviour:
- Ability for a user to edit/upload a new file when viewing a media library item.
- This would keep the same URL (if the filename is the same) and the same file ID regardless.

Keeping the same file ID is important. If there was a way to update the file whilst retaining the same file ID, then I can create a custom route or model, using the API to get files via ID and redirect to the correct file path.

![image](https://user-images.githubusercontent.com/33236577/108273397-6e3f1780-716b-11eb-824d-814cd91c475d.png)

Thanks,

**Comment by classic-o** [comment]
Hi. Thank you. Yes, good idea... At this moment I am not supporting this library... But have a plan to create v2 If you need it now, modify this library manually (as local Nova component)

**Comment by wightspace** [comment]
> Hi. Thank you. Yes, good idea... At this moment I am not supporting this library... But have a plan to create v2 If you need it now, modify this library manually (as local Nova component)

When do you plan to release v2.0?
