### ISSUE TITLE
Forbidden file format error on all image uploads

### ISSUE THREAD

**Issue by Farlandercd** [classic-o/nova-media-library#67]
**Describe the bug**
Getting 'forbidden file format' error when uploading any kind of image.

**To Reproduce**
1. Go to 'Nova Media Library tab'
2. Click on 'Upload'
3. Upload any image (I tried png and jpg)

**Screenshots**
![image](https://user-images.githubusercontent.com/15110811/117576003-72346300-b0e4-11eb-8000-a23d96bff2df.png)

**Additional context**
NGINX and Laravel config are already set to 100mb max file size, furthermore form image uploads on the front end work without problem, likewise does the vanilla Nova Image::make file upload work without problem.

Running Laravel 8 with Laravel Nova v3.23.2 on Laravel Homestead

**Comment by classic-o** [comment]
Hi. Show me your config file and how to use field

**Comment by Farlandercd** [comment]
Hi! What config is it you want? I'm not using a manual field, I am attempting to use the page that comes bundled with this extension.

![image](https://user-images.githubusercontent.com/15110811/117581442-0f02fa80-b0fd-11eb-8d97-e3e657cfb76f.png)
(/nova/media-library)

**Comment by classic-o** [comment]
your config file for media library. Stored in config folder of laravel. 
Did you use install instruction?

**Comment by classic-o** [comment]
You need to set correct configuration. See install instruction
