### ISSUE TITLE
Custom folder based on post

### ISSUE THREAD

**Issue by mostyn-grp** [classic-o/nova-media-library#69]
Hi, First of all thank you for the hard work and providing us with this nova lbrary.

How can i upload images to only show for the post it was uploaded in?

sorry im new and trying to figure this out.

**Comment by classic-o** [comment]
Hi. You can set "store - together" in config, and create folder for posts. And upload all files for posts to these folder

**Comment by mostyn-grp** [comment]
this is my setting:

```

	/**
	 * Store files `together` or in separate `folders`
	 *
	 * @var string
	 */

	'store' => 'together',

	/**
	 * Default file visibility (only for s3)
	 * For disk `local` will be `true`, for `public` - `false`
	 *
	 * @var boolean
	 */

	'private' => false,

	/**
	 * Store all files in a separate folder of storage
	 *
	 * @var string
	 */

	'folder'  => 'listing',

	/**
	 * Organize uploads into date based folders
	 * Available date characters: `Y`, `m`, `d` and symbols: `-`, `_`, `/`
	 * Does not work when parameter `store` != `together`
	 *
	 * @example `Y-m`, `Y/m`, `Y-m/d`
	 * @var string
	 */
```

but i need it to be somethng like:
'folder'  => 'listing/{post_id}',

but the pictures should only show if it was uploaded for that relevent post.

**Comment by classic-o** [comment]
No. Library has no these ability

**Comment by mostyn-grp** [comment]
@classic-o, thank you for your help.
