### ISSUE TITLE
How to save the filename in the model table instead the ID

### ISSUE THREAD

**Issue by MaximeGraindor** [classic-o/nova-media-library#75]
Hello! First of all, thank you for this work and this package!

I have a small question about the save in the database
In the "Nova_media_library" table, the name is saved correctly while in my "photos" table, it's the id that is saved. So when I want to do "$album->photos[0]->path" I get the ID and not the name of the image.

Is it possible to get the file name instead of the image ID? Because when I want to display the path of the image, it does not necessarily find the image

Thanks again, this is exactly the package I needed!

![2](https://user-images.githubusercontent.com/23659663/131043796-595257ba-923a-4443-bb99-215b4f32d5cb.JPG)
![Capture](https://user-images.githubusercontent.com/23659663/131043800-104d6470-780f-4686-9b38-fd73e77b7e2b.JPG)

**Comment by classic-o** [comment]
Hello.
https://github.com/classic-o/nova-media-library#get-files-by-ids

**Comment by MaximeGraindor** [comment]
Alright, my bad, I'll pay more attention to the documentation next time! Sorry for the question and thanks!
