### ISSUE TITLE
"Undefined index: resize" error when uploading images

### ISSUE THREAD

**Issue by kandidaterne** [classic-o/nova-media-library#8]
I followed the setup instructions and when I try to upload an image I get the error "Undefined index: resize" and the text on the button etc look strange...

Can someone tell me what is the Issue here?

<img width="1379" alt="classic_nova_media_library" src="https://user-images.githubusercontent.com/48684660/60340052-d8a9af80-99aa-11e9-84a1-a486207b64ca.png">

**Comment by classic-o** [comment]
Hi, I think you forgot publish the package
`php artisan vendor:publish --provider="ClassicO\NovaMediaLibrary\ToolServiceProvider"`

**Comment by kandidaterne** [comment]
I did the publish command but there is no change, still the same error :-/

**Comment by classic-o** [comment]
Try to reinstall the package. I test it now and I have no problem.

**Comment by kandidaterne** [comment]
Doesn't work. I've updated my Nova version to 2.0.7 and Laravel to 5.8.26. I've reinstalled the package, followed the instructions, and when it comes to migration I get the message: nothing to migrate and the button-text doesn't seem to be translated and are still like the image I've posted previously...

I've no clue :-/

**Comment by classic-o** [comment]
Check files. Do you have in config folder `media-library.php` and in resources/lang/vendor/nova-media-library/en/ `messages.php`. And third file in migration

The tool does not work without these files.

**Comment by kandidaterne** [comment]
I have these files but it still doesn't work :-/ I'm about to give up...

The thing is that some months ago I've installed it already and it did work, but after a short time it was not needed anymore. Now when I want to use it again it doesn't work. When I look at my migrations, the previous _create_nova_media_library_table.php_ migration is untracked and does not get migrated When I create the table manually it still doesn't work.

I alos tried do remove it from my _composer.json: and then run composer update and then install it again but no luck. 

Even php artisan config:cache or php artisan cache:clear

Its really strange...

**Comment by kandidaterne** [comment]
Interesting, when I check the console I get _TypeError: Cannot read property 'length' of undefined_ - which is located in _media-library_

**Comment by classic-o** [comment]
Can you show your project? :)
I think you have problem with application... something went wrong

**Comment by kandidaterne** [comment]
> Can you show your project? :)
> I think you have problem with application... something went wrong

How do you mean show your project?

**Comment by classic-o** [comment]
I can`t help you if I dont see what happend.
With new laravel project and this package everything works well

**Comment by kandidaterne** [comment]
But you don't ask me what you specifically want to see...

**Comment by classic-o** [comment]
I want to see how you broke laravel :)
No, It makes no sense to show me, see where you changed\broke the structure of the laravel nova
