### ISSUE TITLE
Uploading animated gif seems to flatten and use only first frame

### ISSUE THREAD

**Issue by graphem** [classic-o/nova-media-library#80]
When uploading an animated gif it seems to flatten he gif so only the first frame is then use to generate the file for some reason. Wondering if this is a bug of by default?

**Comment by classic-o** [comment]
Hi. yes. I did not do resize for GIF. For preview image cropped without animation. But for website you will use original image with animation.

**Comment by graphem** [comment]
But the issue is if I upload an animated gif, it kill my gif. Any way to avoid this? So that the animated gif remains when stored in our storage?

**Comment by classic-o** [comment]
Use original gif file. Destroys only resized gif images
