### ISSUE TITLE
Documentation to Display Image

### ISSUE THREAD

**Issue by giftbalogun** [classic-o/nova-media-library#81]
**Is your feature request related to a problem? Please describe.**
Hello, i have been trying to retrieve an image i uploaded using the API::getFiles but i only get the storage path the image does not display on the frontend view 

**Describe the solution you'd like**
Add a document on how to retrieve the file or document from the backend and display on the front end view

**Describe alternatives you've considered**

**Additional context**

**Comment by classic-o** [comment]
Hi, insert url to **src** param of **<img>** tag
If you use **private** file, API has **getPrivateFile** method

Please, read readme or comments in class methods
