### ISSUE TITLE
Nova 4 support

### ISSUE THREAD

**Issue by fabiov** [classic-o/nova-media-library#86]
Update library to support Nova 4 release.

**Comment by ali-raza-saleem** [comment]
Hi, I created PR for Nova 4 update. Kindly approve.

**Comment by sutcliffe121** [comment]
Is then PR by @the-alichemist likely to be approved? Would love to continue using this package in Nova 4.

**Comment by classic-o** [comment]
Hello. The library does not support Nova v4 and has not been updated in the last 2 years... I have a plan to release v2 of my package, but I don't know when that will happen.
Currently, you can fork and fix everything
