### ISSUE TITLE
SVG File are not displayed, paperclip instead

### ISSUE THREAD

**Issue by Sorion** [classic-o/nova-media-library#9]
**Describe the bug**
Svg is not display on the media library tab, a paper clip is display instead.
Previous version does support svg file.

**To Reproduce**
1. Go to media library tab
2. Click on 'Upload Files'
3. Select an SVG file
4. Paperclip is display

**Screenshots**
![svgTest](https://user-images.githubusercontent.com/11090914/61526750-56e1fa80-aa1b-11e9-827d-34564192a4d7.PNG)

**Comment by classic-o** [comment]
Hi. Try to add in config file, in param types - images **svg** extension.
`'types'     => [
	'Image'     => [ 'jpg', 'jpeg', 'png', 'gif', 'svg' ]
],`
It works on my site.
Or may be incorrect mime type of your svg? Because image preview shows, when file has mime type - **image**

**Comment by Sorion** [comment]
Hi, 
Thanks, it seems my svg file are not 'true' svg file. I tried with a better source and it's works fine.
